name: Sync From Backend

on:
  # Позволяет запускать этот workflow вручную или через API (из бэкенд-репозитория)
  workflow_dispatch:

jobs:
  sync-directory:
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код фронтенд-репозитория
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BACKEND_ACCESS_TOKEN }}

      # 2. Клонируем бэкенд-репозиторий во временную папку
      - name: Clone Backend Repo
        run: |
          git clone https://${{ secrets.BACKEND_ACCESS_TOKEN }}@github.com/nikrr4000/back-project.git temp-backend

      # 3. Синхронизируем и удаляем временную папку
      - name: Sync Directory and Cleanup
        run: |
          # Создаем директорию назначения, если её нет
          mkdir -p src/config

          # Синхронизируем нужные файлы
          rsync -av --delete temp-backend/src/config/ src/config/

          # СРАЗУ УДАЛЯЕМ ВРЕМЕННУЮ ПАПКУ, ЧТОБЫ ОНА НЕ ПОПАЛА В КОММИТ 👈
          rm -rf temp-backend

      # 4. Проверяем наличие изменений, делаем коммит и пуш
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # ИСПРАВЛЕННОЕ СООБЩЕНИЕ КОММИТА 👈
          commit_message: "chore(sync): Update files from backend repository [skip ci]"

          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"

          # ИСПРАВЛЕННЫЕ ОПЦИИ КОММИТА 👈
          commit_options: "--no-verify --signoff"
